targets:
  $default:
    builders:
      gql_build|schema_builder:
        enabled: true
      gql_build|ast_builder:
        enabled: true
      gql_build|data_builder:
        enabled: true
        options:
          schema: linkbase|lib/schema.graphql
      gql_build|var_builder:
        enabled: true
        options:
          schema: linkbase|lib/schema.graphql
      gql_build|serializer_builder:
        enabled: true
        options:
          schema: linkbase|lib/schema.graphql

      ferry_generator|req_builder:
        enabled: true
        options:
          schema: linkbase|lib/schema.graphql

      build_web_compilers:entrypoint:
        # These are globs for the entrypoints you want to compile.
        generate_for:
        - test/**.browser_test.dart
        - web/**.dart
        options:
          compiler: dart2js
          # List any dart2js specific args here, or omit it.
          dart2js_args:
          - -O1