// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'serializers.gql.dart';

// **************************************************************************
// BuiltValueGenerator
// **************************************************************************

Serializers _$serializers = (new Serializers().toBuilder()
      ..add(GCacheControlScope.serializer)
      ..add(GGetEntityData.serializer)
      ..add(GGetEntityData_wikidata.serializer)
      ..add(GGetEntityData_wikidata_entity.serializer)
      ..add(GGetEntityData_wikidata_entity_claims.serializer)
      ..add(GGetEntityData_wikidata_entity_claims_mainsnak.serializer)
      ..add(
          GGetEntityData_wikidata_entity_claims_mainsnak_datavalue__asSnakValueEntity
              .serializer)
      ..add(
          GGetEntityData_wikidata_entity_claims_mainsnak_datavalue__asSnakValueEntity_SnakValueEntity
              .serializer)
      ..add(
          GGetEntityData_wikidata_entity_claims_mainsnak_datavalue__asSnakValueEntity_SnakValueEntity_description
              .serializer)
      ..add(
          GGetEntityData_wikidata_entity_claims_mainsnak_datavalue__asSnakValueEntity_SnakValueEntity_label
              .serializer)
      ..add(
          GGetEntityData_wikidata_entity_claims_mainsnak_datavalue__asSnakValueGlobeCoordinate
              .serializer)
      ..add(
          GGetEntityData_wikidata_entity_claims_mainsnak_datavalue__asSnakValueGlobeCoordinate_SnakValueGlobeCoordinate
              .serializer)
      ..add(
          GGetEntityData_wikidata_entity_claims_mainsnak_datavalue__asSnakValueGlobeCoordinate_SnakValueGlobeCoordinate_globe
              .serializer)
      ..add(
          GGetEntityData_wikidata_entity_claims_mainsnak_datavalue__asSnakValueGlobeCoordinate_SnakValueGlobeCoordinate_globe_description
              .serializer)
      ..add(
          GGetEntityData_wikidata_entity_claims_mainsnak_datavalue__asSnakValueGlobeCoordinate_SnakValueGlobeCoordinate_globe_label
              .serializer)
      ..add(
          GGetEntityData_wikidata_entity_claims_mainsnak_datavalue__asSnakValueMonolingualText
              .serializer)
      ..add(
          GGetEntityData_wikidata_entity_claims_mainsnak_datavalue__asSnakValueMonolingualText_SnakValueMonolingualText
              .serializer)
      ..add(
          GGetEntityData_wikidata_entity_claims_mainsnak_datavalue__asSnakValuePage
              .serializer)
      ..add(
          GGetEntityData_wikidata_entity_claims_mainsnak_datavalue__asSnakValuePage_SnakValuePage
              .serializer)
      ..add(
          GGetEntityData_wikidata_entity_claims_mainsnak_datavalue__asSnakValueQuantity
              .serializer)
      ..add(
          GGetEntityData_wikidata_entity_claims_mainsnak_datavalue__asSnakValueQuantity_SnakValueQuantity
              .serializer)
      ..add(
          GGetEntityData_wikidata_entity_claims_mainsnak_datavalue__asSnakValueString
              .serializer)
      ..add(
          GGetEntityData_wikidata_entity_claims_mainsnak_datavalue__asSnakValueTime
              .serializer)
      ..add(
          GGetEntityData_wikidata_entity_claims_mainsnak_datavalue__asSnakValueTime_SnakValueTime
              .serializer)
      ..add(
          GGetEntityData_wikidata_entity_claims_mainsnak_datavalue__asSnakValueTime_SnakValueTime_calendarmodel
              .serializer)
      ..add(
          GGetEntityData_wikidata_entity_claims_mainsnak_datavalue__asSnakValueTime_SnakValueTime_calendarmodel_label
              .serializer)
      ..add(GGetEntityData_wikidata_entity_claims_mainsnak_datavalue__base
          .serializer)
      ..add(GGetEntityData_wikidata_entity_claims_mainsnak_property.serializer)
      ..add(GGetEntityData_wikidata_entity_claims_mainsnak_property_description
          .serializer)
      ..add(GGetEntityData_wikidata_entity_claims_mainsnak_property_label
          .serializer)
      ..add(GGetEntityData_wikidata_entity_claims_qualifiers.serializer)
      ..add(
          GGetEntityData_wikidata_entity_claims_qualifiers_datavalue__asSnakValueEntity
              .serializer)
      ..add(
          GGetEntityData_wikidata_entity_claims_qualifiers_datavalue__asSnakValueEntity_SnakValueEntity
              .serializer)
      ..add(
          GGetEntityData_wikidata_entity_claims_qualifiers_datavalue__asSnakValueEntity_SnakValueEntity_description
              .serializer)
      ..add(
          GGetEntityData_wikidata_entity_claims_qualifiers_datavalue__asSnakValueEntity_SnakValueEntity_label
              .serializer)
      ..add(
          GGetEntityData_wikidata_entity_claims_qualifiers_datavalue__asSnakValueGlobeCoordinate
              .serializer)
      ..add(
          GGetEntityData_wikidata_entity_claims_qualifiers_datavalue__asSnakValueGlobeCoordinate_SnakValueGlobeCoordinate
              .serializer)
      ..add(
          GGetEntityData_wikidata_entity_claims_qualifiers_datavalue__asSnakValueGlobeCoordinate_SnakValueGlobeCoordinate_globe
              .serializer)
      ..add(
          GGetEntityData_wikidata_entity_claims_qualifiers_datavalue__asSnakValueGlobeCoordinate_SnakValueGlobeCoordinate_globe_description
              .serializer)
      ..add(
          GGetEntityData_wikidata_entity_claims_qualifiers_datavalue__asSnakValueGlobeCoordinate_SnakValueGlobeCoordinate_globe_label
              .serializer)
      ..add(
          GGetEntityData_wikidata_entity_claims_qualifiers_datavalue__asSnakValueMonolingualText
              .serializer)
      ..add(
          GGetEntityData_wikidata_entity_claims_qualifiers_datavalue__asSnakValueMonolingualText_SnakValueMonolingualText
              .serializer)
      ..add(
          GGetEntityData_wikidata_entity_claims_qualifiers_datavalue__asSnakValuePage
              .serializer)
      ..add(
          GGetEntityData_wikidata_entity_claims_qualifiers_datavalue__asSnakValuePage_SnakValuePage
              .serializer)
      ..add(
          GGetEntityData_wikidata_entity_claims_qualifiers_datavalue__asSnakValueQuantity
              .serializer)
      ..add(
          GGetEntityData_wikidata_entity_claims_qualifiers_datavalue__asSnakValueQuantity_SnakValueQuantity
              .serializer)
      ..add(
          GGetEntityData_wikidata_entity_claims_qualifiers_datavalue__asSnakValueString
              .serializer)
      ..add(
          GGetEntityData_wikidata_entity_claims_qualifiers_datavalue__asSnakValueTime
              .serializer)
      ..add(
          GGetEntityData_wikidata_entity_claims_qualifiers_datavalue__asSnakValueTime_SnakValueTime
              .serializer)
      ..add(
          GGetEntityData_wikidata_entity_claims_qualifiers_datavalue__asSnakValueTime_SnakValueTime_calendarmodel
              .serializer)
      ..add(
          GGetEntityData_wikidata_entity_claims_qualifiers_datavalue__asSnakValueTime_SnakValueTime_calendarmodel_label
              .serializer)
      ..add(GGetEntityData_wikidata_entity_claims_qualifiers_datavalue__base
          .serializer)
      ..add(
          GGetEntityData_wikidata_entity_claims_qualifiers_property.serializer)
      ..add(
          GGetEntityData_wikidata_entity_claims_qualifiers_property_description
              .serializer)
      ..add(GGetEntityData_wikidata_entity_claims_qualifiers_property_label
          .serializer)
      ..add(GGetEntityData_wikidata_entity_claims_references.serializer)
      ..add(GGetEntityData_wikidata_entity_claims_references_snaks.serializer)
      ..add(
          GGetEntityData_wikidata_entity_claims_references_snaks_datavalue__asSnakValueEntity
              .serializer)
      ..add(
          GGetEntityData_wikidata_entity_claims_references_snaks_datavalue__asSnakValueEntity_SnakValueEntity
              .serializer)
      ..add(
          GGetEntityData_wikidata_entity_claims_references_snaks_datavalue__asSnakValueEntity_SnakValueEntity_description
              .serializer)
      ..add(
          GGetEntityData_wikidata_entity_claims_references_snaks_datavalue__asSnakValueEntity_SnakValueEntity_label
              .serializer)
      ..add(
          GGetEntityData_wikidata_entity_claims_references_snaks_datavalue__asSnakValueGlobeCoordinate
              .serializer)
      ..add(
          GGetEntityData_wikidata_entity_claims_references_snaks_datavalue__asSnakValueGlobeCoordinate_SnakValueGlobeCoordinate
              .serializer)
      ..add(
          GGetEntityData_wikidata_entity_claims_references_snaks_datavalue__asSnakValueGlobeCoordinate_SnakValueGlobeCoordinate_globe
              .serializer)
      ..add(
          GGetEntityData_wikidata_entity_claims_references_snaks_datavalue__asSnakValueGlobeCoordinate_SnakValueGlobeCoordinate_globe_description
              .serializer)
      ..add(
          GGetEntityData_wikidata_entity_claims_references_snaks_datavalue__asSnakValueGlobeCoordinate_SnakValueGlobeCoordinate_globe_label
              .serializer)
      ..add(
          GGetEntityData_wikidata_entity_claims_references_snaks_datavalue__asSnakValueMonolingualText
              .serializer)
      ..add(
          GGetEntityData_wikidata_entity_claims_references_snaks_datavalue__asSnakValueMonolingualText_SnakValueMonolingualText
              .serializer)
      ..add(
          GGetEntityData_wikidata_entity_claims_references_snaks_datavalue__asSnakValuePage
              .serializer)
      ..add(
          GGetEntityData_wikidata_entity_claims_references_snaks_datavalue__asSnakValuePage_SnakValuePage
              .serializer)
      ..add(
          GGetEntityData_wikidata_entity_claims_references_snaks_datavalue__asSnakValueQuantity
              .serializer)
      ..add(
          GGetEntityData_wikidata_entity_claims_references_snaks_datavalue__asSnakValueQuantity_SnakValueQuantity
              .serializer)
      ..add(
          GGetEntityData_wikidata_entity_claims_references_snaks_datavalue__asSnakValueString
              .serializer)
      ..add(
          GGetEntityData_wikidata_entity_claims_references_snaks_datavalue__asSnakValueTime
              .serializer)
      ..add(
          GGetEntityData_wikidata_entity_claims_references_snaks_datavalue__asSnakValueTime_SnakValueTime
              .serializer)
      ..add(
          GGetEntityData_wikidata_entity_claims_references_snaks_datavalue__asSnakValueTime_SnakValueTime_calendarmodel
              .serializer)
      ..add(
          GGetEntityData_wikidata_entity_claims_references_snaks_datavalue__asSnakValueTime_SnakValueTime_calendarmodel_label
              .serializer)
      ..add(
          GGetEntityData_wikidata_entity_claims_references_snaks_datavalue__base
              .serializer)
      ..add(GGetEntityData_wikidata_entity_claims_references_snaks_property
          .serializer)
      ..add(
          GGetEntityData_wikidata_entity_claims_references_snaks_property_description
              .serializer)
      ..add(
          GGetEntityData_wikidata_entity_claims_references_snaks_property_label
              .serializer)
      ..add(GGetEntityData_wikidata_entity_description.serializer)
      ..add(GGetEntityData_wikidata_entity_label.serializer)
      ..add(GGetEntityReq.serializer)
      ..add(GGetEntityVars.serializer)
      ..add(GPageExtractSectionFormat.serializer)
      ..add(GSnakFragmentData.serializer)
      ..add(GSnakFragmentData_datavalue__asSnakValueEntity.serializer)
      ..add(GSnakFragmentData_datavalue__asSnakValueEntity_SnakValueEntity
          .serializer)
      ..add(
          GSnakFragmentData_datavalue__asSnakValueEntity_SnakValueEntity_description
              .serializer)
      ..add(GSnakFragmentData_datavalue__asSnakValueEntity_SnakValueEntity_label
          .serializer)
      ..add(GSnakFragmentData_datavalue__asSnakValueGlobeCoordinate.serializer)
      ..add(
          GSnakFragmentData_datavalue__asSnakValueGlobeCoordinate_SnakValueGlobeCoordinate
              .serializer)
      ..add(
          GSnakFragmentData_datavalue__asSnakValueGlobeCoordinate_SnakValueGlobeCoordinate_globe
              .serializer)
      ..add(
          GSnakFragmentData_datavalue__asSnakValueGlobeCoordinate_SnakValueGlobeCoordinate_globe_description
              .serializer)
      ..add(
          GSnakFragmentData_datavalue__asSnakValueGlobeCoordinate_SnakValueGlobeCoordinate_globe_label
              .serializer)
      ..add(GSnakFragmentData_datavalue__asSnakValueMonolingualText.serializer)
      ..add(
          GSnakFragmentData_datavalue__asSnakValueMonolingualText_SnakValueMonolingualText
              .serializer)
      ..add(GSnakFragmentData_datavalue__asSnakValuePage.serializer)
      ..add(
          GSnakFragmentData_datavalue__asSnakValuePage_SnakValuePage.serializer)
      ..add(GSnakFragmentData_datavalue__asSnakValueQuantity.serializer)
      ..add(GSnakFragmentData_datavalue__asSnakValueQuantity_SnakValueQuantity
          .serializer)
      ..add(GSnakFragmentData_datavalue__asSnakValueString.serializer)
      ..add(GSnakFragmentData_datavalue__asSnakValueTime.serializer)
      ..add(
          GSnakFragmentData_datavalue__asSnakValueTime_SnakValueTime.serializer)
      ..add(
          GSnakFragmentData_datavalue__asSnakValueTime_SnakValueTime_calendarmodel
              .serializer)
      ..add(
          GSnakFragmentData_datavalue__asSnakValueTime_SnakValueTime_calendarmodel_label
              .serializer)
      ..add(GSnakFragmentData_datavalue__base.serializer)
      ..add(GSnakFragmentData_property.serializer)
      ..add(GSnakFragmentData_property_description.serializer)
      ..add(GSnakFragmentData_property_label.serializer)
      ..add(GSnakFragmentReq.serializer)
      ..add(GSnakFragmentVars.serializer)
      ..add(GUpload.serializer)
      ..addBuilderFactory(
          const FullType(BuiltList,
              const [const FullType(GGetEntityData_wikidata_entity_claims)]),
          () => new ListBuilder<GGetEntityData_wikidata_entity_claims>())
      ..addBuilderFactory(
          const FullType(BuiltList, const [
            const FullType(GGetEntityData_wikidata_entity_claims_qualifiers)
          ]),
          () => new ListBuilder<
              GGetEntityData_wikidata_entity_claims_qualifiers>())
      ..addBuilderFactory(
          const FullType(BuiltList, const [
            const FullType(GGetEntityData_wikidata_entity_claims_references)
          ]),
          () => new ListBuilder<
              GGetEntityData_wikidata_entity_claims_references>())
      ..addBuilderFactory(
          const FullType(BuiltList, const [
            const FullType(
                GGetEntityData_wikidata_entity_claims_references_snaks)
          ]),
          () => new ListBuilder<
              GGetEntityData_wikidata_entity_claims_references_snaks>()))
    .build();

// ignore_for_file: always_put_control_body_on_new_line,always_specify_types,annotate_overrides,avoid_annotating_with_dynamic,avoid_as,avoid_catches_without_on_clauses,avoid_returning_this,deprecated_member_use_from_same_package,lines_longer_than_80_chars,omit_local_variable_types,prefer_expression_function_bodies,sort_constructors_first,test_types_in_equals,unnecessary_const,unnecessary_new
